export const actionTypes = {
  SET_LOADING: 'SET_LOADING',
  SET_APP_THEME: "SET_APP_THEME",
  SET_DENTISTS_DATA: 'SET_DENTIST_DATA',
  ADD_FAVORITE_DENTIST: 'ADD_FAVORITE_DENTIST',
  DELETE_FAVORITE_DENTIST: 'DELETE_FAVORITE_DENTIST',
};
